abentstvo_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from contacts.views import contacts_views
from homes.views import list_views, detail_view

from abentstvo_project import settings
from search.views import search_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homes.urls', namespace='homes')),
    path('search/', include('search.urls', namespace='search')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('api/', include('api.urls', namespace='api'))
]

if settings.DEBUG is True:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import HomesApi

app_name = 'api'

router = routers.DefaultRouter()
router.register('homes', HomesApi)

urlpatterns = [
    path('', include(router.urls))
]

contacts/urls.py
from django.urls import path

from contacts.views import contacts_views

app_name = 'contacts'
urlpatterns = [
    path('', contacts_views, name='main')
]

homes/urls.py
from django.urls import path

from homes.views import list_views, detail_view

app_name = 'homes'

urlpatterns = [
    path('', list_views, name='main_page'),
    path('home/<int:pk>', detail_view, name='detail_page'),
]

search/urls.py
from django.urls import path

from search.views import search_views

app_name = 'search'
urlpatterns = [
    path('', search_views, name='main')
]

api/models.py
from django.db import models

# Create your models here.

application/models.py
from django.db import models

# Create your models here.


class Application(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    question = models.TextField()
    manager_id = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} / {self.name} / {self.manager_id}'

contacts/models.py
from django.db import models

# Create your models here.

homes/models.py
from django.db import models
from django.urls import reverse

from managers.models import Manager


class Category(models.Model):
    category = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.pk} - {self.category}'


class Home(models.Model):
    title = models.CharField(max_length=200, blank=True,null=True)
    info = models.TextField()
    s = models.FloatField()
    district = models.CharField(max_length=200)
    cost = models.IntegerField()
    img = models.ImageField(upload_to='img', blank=True, null=True)
    manager = models.ForeignKey(Manager, on_delete=models.PROTECT, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('homes:detail_page', args=[self.id])

managers/models.py
from django.db import models

class Manager(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    img = models.ImageField(upload_to='manager_img')

    def __str__(self):
        return f'{self.id}  {self.first_name}'

search/models.py
from django.db import models

# Create your models here.

application/forms.py
from django import forms

from application.models import Application


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['name', 'email', 'question', 'manager_id']

api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

from api.serializers import HomeSerializer
from homes.models import Home


# Create your views here.


class HomesApi(viewsets.ModelViewSet):
    permission_classes = [AllowAny]
    queryset = Home.objects.all()
    serializer_class = HomeSerializer
    # http_method_names = ['get']

application/views.py
from django.shortcuts import render

# Create your views here.

contacts/views.py
from django.shortcuts import render

def contacts_views(request):
    return render(request, 'contacts.html')

homes/views.py
from django.shortcuts import render, redirect

from application.forms import ApplicationForm
from homes.models import Home


def list_views(request):
    homes = Home.objects.all()
    return render(request, 'index.html', {'homes': homes})


def detail_view(request, pk):
    home = Home.objects.get(id=pk)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('homes:main_page')
    else:
        form = ApplicationForm()

    return render(request, 'detail.html', {'home': home, 'form': form})

managers/views.py
from django.shortcuts import render

# Create your views here.

search/views.py
from django.db.models import Q
from django.shortcuts import render

from homes.models import Home, Category


def search_views(request):
    query = request.GET.get('q')
    max = request.GET.get('max')
    min = request.GET.get('min')
    cat_id = request.GET.get('category')
    categories = Category.objects.all()

    if query:
        words = query.split()
        q_objects = Q()
        for word in words:
            q_objects &= (Q(info__iregex=word) | Q(title__iregex=word))
        homes = Home.objects.filter(q_objects)


        #homes = Home.objects.filter(Q(info__iregex=query) | Q(title__iregex=query))
    else:
        homes = Home.objects.all()

    if max:
        homes = homes.filter(cost__lte=max)

    if min:
        homes = homes.filter(cost__gte=min)

    if cat_id:
        homes = homes.filter(category=cat_id)


    return render(request, 'search.html', {'homes': homes, 'categories': categories})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Магазин товаров</title>
  <!-- Подключение Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/butstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/customcss.css' %}">


</head>
<body>
  <header>
    <!-- Верхнее меню -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'homes:main_page' %}">AstanaRealty</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homes:main_page' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'search:main' %}">Поиск</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts:main' %}">Контакты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>




    {% block content %}
    {% endblock %}



  <footer>
    <!-- Футер -->
    <div class="container">
      <p class="footer-text">&copy; 2023 Магазин товаров. Все права защищены. | Разработано <a href="#" class="footer-link">Вашеимя</a></p>
    </div>
  </footer>

  <!-- Подключение скриптов Bootstrap -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

templates/contacts.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <br>


  <h1> Страница контактов </h1>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}

<br>
<br>

<div class="container">
    <div class="row">
        <!-- Колонка с описанием -->
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ home.title }}</h5>
                    <h5 class="card-title">{{ home.s }} кв/м</h5>
                    <h5 class="card-title">Район {{ home.district }}</h5>
                    <h5 class="card-title">Цена {{ home.cost }}</h5>
                    <p class="card-text">{{ home.info }}</p>
                    <p class="card-text">Мэн Дэджер: {{ home.manager }}</p>
                </div>
            </div>
        </div>

        <!-- Колонка с картой -->
        <div class="col-md-4">
            <div class="card">
                <!--  код для блока с картой здесь -->
                <div class="map">
                    <!--  код для карты здесь -->
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Колонка с изображением -->
        <div class="col-md-4">
            <div class="card">
                {% if home.img %}
                <img src="{{ home.img.url }}" class="card-img-top" alt="Товар 1">
                {% else %}
                <img src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" class="card-img-top" alt="Товар 1">
                {% endif %}
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                {% if home.img %}
                <img src="{{ home.img.url }}" class="card-img-top" alt="Товар 1">
                {% else %}
                <img src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" class="card-img-top" alt="Товар 1">
                {% endif %}
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                {% if home.img %}
                <img src="{{ home.img.url }}" class="card-img-top" alt="Товар 1">
                {% else %}
                <img src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" class="card-img-top" alt="Товар 1">
                {% endif %}
            </div>
        </div>
    </div>
</div>


<div class="container">
    <form action="" method="post">
        {% csrf_token %}

        <input name="name" placeholder="name">
        <input name="email" placeholder="email">
        <input name="question" placeholder="question">
        <input name="manager_id" placeholder="manager_id">

        <button type="submit"> Submit </button>
    </form>
</div>




{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Фото по ширине страницы -->
    <div class="header-image">
      <img src="{% static 'img/banner_1.jpg' %}" class="header-image" alt="Фото">
      <div class="header-content">
        <h1 class="header-title">Недвижимость для всех!</h1>
{#        <a href="#" class="header-button">Подобрать</a>#}
      </div>
    </div>
  </header>
  <br>
  <br>
  <!-- карточки товара -->
  <div class="container">
    <div class="row">

      {% for home in homes %}
      <div class="col-md-4">
        <div class="card">

          {% if home.img %}
          <a href="{{ home.get_absolute_url }}"><img src="{{ home.img.url }}" class="card-img-top" alt="Товар 1"></a>
          {% else %}
          <a href="{{ home.get_absolute_url }}"><img src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" class="card-img-top" alt="Товар 1"></a>
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ home.title }}</h5>
            <p class="card-text">{{ home.info|truncatewords:10 }}</p>




          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block content %}


  <br>
  <br>
    <div class="container">
        <form action="" method="get">

        <select name="category" class="form-control" onchange="this.form.submit()">
            <option value="">Тип недвижимости</option>
                {% for i in categories %}
                   <option value="{{ i.pk }}" {% if request.GET.category|stringformat:"s" == i.pk|stringformat:"s" %}selected{% endif %}>{{ i }}</option>
                {% endfor %}
        </select>


            <input name="q" placeholder="text search" value="{{ request.GET.q }}">
            <input name="max" placeholder="max price" value="{{ request.GET.max }}">
            <input name="min" placeholder="min price" value="{{ request.GET.min }}">
            <button type="submit"> Search </button>
        </form>



    </div>
  <br>
  <br>
  <!-- карточки товара -->
  <div class="container">
    <div class="row">

      {% for home in homes %}
      <div class="col-md-4">
        <div class="card">

          {% if home.img %}
          <a href="{{ home.get_absolute_url }}"><img src="{{ home.img.url }}" class="card-img-top" alt="Товар 1"></a>
          {% else %}
          <a href="{{ home.get_absolute_url }}"><img src="https://edit.org/images/cat/book-covers-big-2019101610.jpg" class="card-img-top" alt="Товар 1"></a>
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ home.title }}</h5>
            <h5 class="card-title">{{ home.cost }}</h5>
            <p class="card-text">{{ home.info|truncatewords:10 }}</p>

          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
{% endblock %}